version: 2

models:
  - name: dim_date
    description: "Generates a date dimension table covering the range from 2023-01-01 to 2026-12-31."

  - name: dim_host
    description: "Processes and cleans host data, ensuring unique hosts with valid information."
    columns:
      - name: host_id
        description: "Unique identifier for the host."
        type: bigint
      - name: host_url
        description: "URL of the host's profile."
        type: text
      - name: host_name
        description: "Name of the host."
        type: text
      - name: host_since
        description: "Date when the host joined the platform."
        type: date
      - name: host_location
        description: "Location of the host."
        type: text
      - name: host_about
        description: "Description or bio of the host."
        type: text
      - name: host_response_time
        description: "Average response time of the host."
        type: text
      - name: host_response_rate
        description: "Response rate of the host."
        type: text
      - name: host_acceptance_rate
        description: "Acceptance rate of the host."
        type: text
      - name: host_is_superhost
        description: "Boolean indicating if the host is a superhost."
        type: boolean
      - name: host_thumbnail_url
        description: "URL of the host's thumbnail picture."
        type: text
      - name: host_picture_url
        description: "URL of the host's full-size picture."
        type: text
      - name: host_neighbourhood
        description: "Neighbourhood where the host is located."
        type: text
      - name: host_listings_count
        description: "Count of the host's active listings."
        type: integer
      - name: host_total_listings_count
        description: "Total count of the host's listings (active and inactive)."
        type: integer
      - name: host_verifications
        description: "List of verifications for the host."
        type: text
      - name: host_has_profile_pic
        description: "Boolean indicating if the host has a profile picture."
        type: boolean
      - name: host_identity_verified
        description: "Boolean indicating if the host's identity is verified."
        type: boolean

  - name: dim_listing
    description: "Processes and cleans listing data, ensuring valid neighbourhood associations."
    columns:
      - name: listing_id
        description: "Unique identifier for the listing."
        type: bigint
      - name: listing_url
        description: "URL of the listing."
        type: text
      - name: source
        description: "Source of the listing (e.g., Airbnb)."
        type: text
      - name: name
        description: "Name or title of the listing."
        type: text
      - name: description
        description: "Description of the listing."
        type: text
      - name: neighborhood_overview
        description: "Overview of the neighbourhood where the listing is located."
        type: text
      - name: picture_url
        description: "URL of the listing's picture."
        type: text
      - name: latitude
        description: "Latitude coordinate of the listing."
        type: numeric
      - name: longitude
        description: "Longitude coordinate of the listing."
        type: numeric
      - name: property_type
        description: "Type of property (e.g., apartment, house)."
        type: text
      - name: room_type
        description: "Type of room available for booking (e.g., entire home, private room)."
        type: text
      - name: accommodates
        description: "Number of guests the listing accommodates."
        type: integer
      - name: bathrooms
        description: "Number of bathrooms in the listing."
        type: numeric
      - name: bathrooms_text
        description: "Text description of the bathrooms (e.g., shared, ensuite)."
        type: text
      - name: bedrooms
        description: "Number of bedrooms in the listing."
        type: integer
      - name: beds
        description: "Number of beds available in the listing."
        type: integer
      - name: amenities
        description: "List of amenities available in the listing."
        type: text
      - name: neighbourhood_cleansed
        description: "Cleansed version of the neighbourhood name."
        type: text
      - name: neighbourhood_id
        description: "Foreign key linking to the neighbourhood dimension."
        type: text



  - name: dim_neighbourhood
    description: "This model processes neighbourhood data, generating a unique ID for each neighbourhood and organizing geographic information."
    columns:
      - name: neighbourhood_id
        description: "Unique identifier for the neighbourhood, generated using ROW_NUMBER()."
        type: integer
      - name: neighbourhood_group
        description: "Name of the neighbourhood group (e.g., district or region)."
        type: text
      - name: neighbourhood
        description: "Name of the specific neighbourhood."
        type: text
      - name: geometry
        description: "Geographic boundary or coordinates of the neighbourhood."
        type: geometry
      - name: row_id
        type: text


  - name: dim_reviewer
    description: "Processes and cleans reviewer data, extracting first and last names."
    columns:
      - name: reviewer_id
        description: "Unique identifier for the reviewer."
        type: bigint
      - name: reviewer_name
        description: "Name of the reviewer, cleaned and standardized."
        type: text
      - name: reviewer_first_name
        description: "First name of the reviewer."
        type: text
      - name: reviewer_last_name
        description: "Last name of the reviewer."
        type: text


